data:
  dataset: "AMOS"
  data_dir: "/home/vargas/amos22"
  split_json: "dataset.json"
model:
  in_channels: 1
  out_channels: 11
  feature_size: 48
  embed_dim_final: 128
training:
  batch_size: 6
  lr: 1e-4
  max_iterations: 30000
  eval_num: 10
  checkpoint_dir: "./outputs/amos/memoryV2"
  pretrained_weights: "./weights/model_swinvit.pt"
  use_memory_bank: True  
  feature_layer: "enc3"
  similarity_threshold: 0.7 
  memory_size: 500
  resume: True
prototype_test:
  batch_size: 2
  checkpoint_dir: "./outputs/amos/prototypes"
  pretrained_weights: "./outputs/amos/prototypes/checkpoint_epoch_10.pth"
