data:
  dataset: "BRATS"
  data_dir: "datasets/BRATS/"
  split_json: "dataset.json"
model:
  in_channels: 4
  out_channels: 2
  feature_size: 48
  embed_dim_final: 128
training:
  batch_size: 8
  lr: 1e-4
  max_iterations: 15000
  eval_num: 10
  checkpoint_dir: "./outputs/brats/memoryV2"
  pretrained_weights: "./weights/model_swinvit.pt"
  use_memory_bank: True  
  similarity_threshold: 0.7 
  feature_layer: "enc3"
  memory_size: 500

